=== Donfuretto/TecWeb-Scout_W3C_WCAG-2_AAA/public_html/news.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.portoconte1.it" targetNamespace="http://www.portoconte1.it" elementFormDefault="qualified">

	<xsd:element name="notizie" type="articoli"/>
	<xsd:complexType name="articoli">
				<xsd:sequence maxOccurs="unbounded">
					<xsd:element name="notizia" type="articolo"/>
				</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="articolo">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:string"/>
			<xsd:element name="titolo" type="xsd:string"/>
			<xsd:element name="data" type="xsd:string"/>
			<xsd:element name="img" type="xsd:string"/>
			<xsd:element name="alt_img" type="xsd:string"/>
			<xsd:element name="corpo" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>		

</xsd:schema>

=== Donfuretto/TecWeb-Scout_W3C_WCAG-2_AAA/public_html/news.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="news.xsl"?>
<d:notizie xmlns="http://www.portoconte1.it" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:d="http://www.portoconte1.it" xsd:schemaLocation="http://www.portoconte1.it news.xsd">

    
    
     
    
          

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	<notizia>
      	<id>1</id>
      	<titolo>La tenda di Abramo, nel cuore della citta</titolo>
      	<data>2015-02-08</data>
      	<img>tenda_de.jpg</img>
      	<alt_img>Una tenda nel cuore del deserto africano</alt_img>
      	<corpo>Nel cuore di Porto Conte fa capolino la tenda di Abramo, che ospiter&#xE0; una lettura collettiva e continua del Libro dei Salmi. Una maratona di 24 ore, che prender&#xE0; il via alle 16.22 di venerd&#xEC; 1 marzo e si concluder&#xE0; alle 11 di sabato 2 marzo. Mi raccomando, non mancare!!</corpo>
      
	</notizia>

	<notizia>
      	<id>2</id>
      	<titolo>Ritrovo con i Capi</titolo>
      	<data>2015-02-08</data>
      	<img>rassegna-620x238.jpg</img>
      	<alt_img>Un giornale appoggiato su un PC portatile</alt_img>
      	<corpo>Luned&#xEC; 23 febbraio i capi si raduneranno per organizzare tutti gli eventi che si terranno durante il mese di marzo. Invitiamo tutti i compagni scout e i genitori dei pi&#xF9; piccoli a venire. Il ritrovo &#xE8; alle ore 16.00 nella sede del gruppo. A fine riunione, ci sar&#xE0; una pizzata con tutti coloro che vorranno restare. Per maggiori informazioni, vi preghiamo di contattarci. A presto!</corpo>
      
	</notizia>

	<notizia>
      	<id>3</id>
      	<titolo>Salviamo i Panda &#x2013; Branco Frate Fuoco</titolo>
      	<data>2015-02-08</data>
      	<img>DSC_7938-620x413.jpg</img>
      	<alt_img>Due ragazze truccate da panda</alt_img>
      	<corpo>Il direttore dell&#x2019;oasi ha fatto imprigionare la biologa Marie dalle guardie di sicurezza, e si incontra con loschi figuri. Dalla valigetta del direttore saltano fuori strani messaggi in codice e progetti di macchinari diabolici inchiodano il direttore alle sue responsabilit&#xE0;. Nel frattempo Jaro, il guardiano dei panda, &#xE8; ignaro di tutto. Non mancate a questa incredibile avventura che si terr&#xE0; nel cuore di Porto Conte. Vi aspettiamo numerosi sabato 28 frebbario!</corpo>
      
	</notizia>
</d:notizie>
